# Generated by Django 5.1.3 on 2024-12-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_aadhar_number_bank_bank_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='Pin_No',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
