# Generated by Django 5.1.3 on 2024-12-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bank_pin_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
